# Generated by Django 3.1.2 on 2020-10-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('id', models.CharField(help_text='ID of squirrel', max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.CharField(help_text='Latitude', max_length=100)),
                ('longtitude', models.CharField(help_text='Longtitude', max_length=100)),
            ],
        ),
    ]
