# Generated by Django 3.1.2 on 2020-10-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('latitude', models.CharField(max_length=100)),
                ('longtitude', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('primary_fur_color', models.CharField(max_length=20)),
                ('highlight_fur_color', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
            ],
        ),
    ]
