# Generated by Django 3.1.2 on 2020-10-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201013_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='highlight_fur_color',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(),
        ),
    ]
