# Generated by Django 3.1.2 on 2020-10-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0008_auto_20201013_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
