# Generated by Django 3.1.2 on 2020-10-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0011_auto_20201013_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
